visual-recognition:
    api-key: 16f89fdfb2940ca1d30e4b1d39c82c82cf5acd5a
clarifai:
    client-id: -RicyiV-SVf5xczPWecv2Wa3iQcFMEtSMWQmp3TP
    client-secret: 5L11J9Y2vfY-mwrj-pmOutQTzSllJy0gEhMAPgGN

